[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

[lib]
name = "lexer2"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_bindgen = "0.7.0"
logos = "0.12.1"
serde = { version = "1", features = ["derive"] }
